### PR TITLE
This is to catch up the progress for develop branch.

### PR DESCRIPTION
**Pull request by linmic**
In git-flow, develop branch is for developing ahead of the master branch, therefore we need to catch up the progress of the develop branch to be even with our master. Then we should develop in the develop branch so that the master will never be ahead of develop.

### CODE REVIEW

**Comment by adammunoz** [comment]
@linmic Do you mean that master was ahead of develop??

**Comment by adammunoz** [comment]
@linmic Do you mean that master was ahead of develop??

**Comment by linmic** [comment]
Yes.

**Comment by adammunoz** [comment]
Oh, it's by mistake. Yes, should be fixed.

**Pull request merged**
